apiVersion: v2
name: speedtest-tracker
description: A Helm chart for Speedtest Tracker, a self-hosted speed test tracking application
type: application
version: 1.0.1
appVersion: "1.13.10"
kubeVersion: ">=1.19.0"
keywords:
  - speedtest-tracker
  - speedtest
  - network
  - monitoring
home: https://github.com/alexjustesen/speedtest-tracker
sources:
  - https://gitlab.example.com/homelab/helm-charts/-/tree/main/charts/speedtest-tracker
  - https://github.com/alexjustesen/speedtest-tracker
maintainers:
  - name: maintainer
    email: maintainer@example.com
    url: https://gitlab.example.com/homelab/helm-charts
